/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.41.0.0
 *
 * Project: 'Blinky' 
 * Target:  'LPC1857 RAM' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "LPC18xx.h"

/* Keil::Device:Startup@1.0.0 */
#define RTE_DEVICE_STARTUP_LPC18XX      /* Device Startup for NXP18XX */


#endif /* RTE_COMPONENTS_H */
